# Generated by Django 2.2.7 on 2019-11-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.BigIntegerField(default=0, verbose_name='Số tiền giảm giá'),
        ),
    ]
