# Generated by Django 2.2.7 on 2019-11-30 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Coupon'),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
