# Generated by Django 2.2.7 on 2019-12-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20191201_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotdeal',
            name='start_deal',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày bắt đầu'),
        ),
    ]
