# Generated by Django 2.2.7 on 2019-12-01 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20191201_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotdeal',
            name='start_deal',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
