# Generated by Django 2.2.7 on 2019-12-01 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20191201_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotdeal',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Product', unique=True),
        ),
    ]
