# Generated by Django 2.2.7 on 2019-12-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20191201_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotdeal',
            name='product',
        ),
    ]
