# Generated by Django 2.2.7 on 2019-12-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_auto_20191201_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotdeal',
            name='start_deal',
        ),
    ]
