# Generated by Django 2.2.7 on 2019-12-01 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_remove_hotdeal_start_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdeal',
            name='start_deal',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
