# Generated by Django 2.2.7 on 2019-12-08 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productsize'),
        ('homepage', '0020_auto_20191208_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotdeal',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotdeal', to='products.Product'),
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_deal', models.DateTimeField(verbose_name='Ngày bắt đầu giảm giá')),
                ('end_deal', models.DateTimeField(verbose_name='Ngày hết')),
                ('available', models.BooleanField(default=True)),
                ('discount_price', models.IntegerField(verbose_name='Giảm giá (%)')),
                ('save_price', models.BigIntegerField(blank=True, editable=False)),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialoffer', to='products.Product')),
            ],
            options={
                'verbose_name': 'Ưu Đãi',
                'verbose_name_plural': 'specialoffer',
            },
        ),
    ]
