# Generated by Django 2.2.7 on 2019-12-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_auto_20191208_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialoffer',
            options={'verbose_name': 'Ưu Đãi', 'verbose_name_plural': 'Ưu đãi đặc biệt'},
        ),
    ]
