# Generated by Django 2.2.7 on 2019-11-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191128_0515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Sản Phẩm'},
        ),
    ]
