# Generated by Django 2.2.7 on 2019-11-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191128_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='title',
            field=models.CharField(default='iphone', max_length=200, verbose_name='Tên bộ ảnh'),
            preserve_default=False,
        ),
    ]
