# Generated by Django 2.2.7 on 2019-11-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên ')),
            ],
            options={
                'verbose_name_plural': 'Tính năng Sản Phẩm',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.TextField(default='Chống thấm nước'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('0', 'News'), ('25', '25%'), ('15', '15%')], max_length=20),
        ),
    ]
