# Generated by Django 2.2.7 on 2019-11-29 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20191129_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='title',
        ),
    ]
