# Generated by Django 2.2.7 on 2019-11-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_productimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Giảm giá (%)'),
        ),
    ]
