# Generated by Django 2.2.7 on 2019-11-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20191129_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Giá'),
        ),
    ]
