# Generated by Django 2.2.7 on 2019-11-29 17:33

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20191129_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumb',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=5000, verbose_name='Image'),
        ),
    ]
