# Generated by Django 2.2.7 on 2019-11-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20191130_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Giảm giá (%)'),
        ),
    ]
