# Generated by Django 2.2.7 on 2019-11-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20191130_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhãn hiệu')),
            ],
            options={
                'verbose_name_plural': 'Nhãn Hiệu',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='products.Brand'),
        ),
    ]
