# Generated by Django 2.2.7 on 2019-12-01 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20191130_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Dòng sản phẩm')),
            ],
            options={
                'verbose_name_plural': 'Dòng Sản Phẩm',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='productfamily',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productfamily', to='products.ProductFamily'),
        ),
    ]
