# Generated by Django 2.2.7 on 2019-12-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên: ')),
                ('price', models.BigIntegerField(null=True, verbose_name='Giá')),
            ],
        ),
    ]
