# Generated by Django 2.2.7 on 2019-12-20 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_stock', models.BooleanField(default=True, verbose_name='Trạng Thái Trong Kho')),
                ('in_stock', models.IntegerField(default=1, verbose_name='Số lượng sản phẩm trong kho')),
                ('is_sold', models.IntegerField(default=0, verbose_name='Số Lượng đã bán')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.Product')),
            ],
            options={
                'verbose_name': 'Kho Hàng',
                'verbose_name_plural': 'Kho Hàng',
            },
        ),
    ]
