# Generated by Django 2.2.7 on 2019-12-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_productfamily'),
        ('products', '0030_auto_20191220_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='productfamily',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands_PF', to='categories.ProductFamily'),
        ),
    ]
