# Generated by Django 2.2.7 on 2019-12-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_brand_productfamily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productfamily',
        ),
    ]
