# Generated by Django 2.2.7 on 2019-11-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCat', models.CharField(max_length=5000, unique=True, verbose_name='Tên Thể Loai')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Ngày Tạo')),
                ('featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Thể Loại',
            },
        ),
    ]
